### ISSUE TITLE
Add support for custom domains

### ISSUE THREAD

**Issue by mads-hartmann** [hatch-sh/hatch#3]
In order to support custom domains you have to created a Hosted Zone in Route53 for the domain and create an A record that points to the CloudFront distribution.

**Comment by skovhus** [comment]
It seems amazon doesn't support a lot of country top domains. See http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/registrar-tld-list.html#D

@mads-hartmann So as a user of Hatch/AWS how would I get my website waldhaus.dk to point to the things we create with hatch? What are the steps? It is possible?
