### ISSUE TITLE
Create hatch organisation

### ISSUE THREAD

**Issue by mads-hartmann** [hatch-sh/hatch#36]
- [x] Create hatch organisation and add Kenneth as administration
- [x] Create a separate repository for the Homebrew formula
- [x] Create a separate repository for the website

**Comment by mads-hartmann** [comment]
@skovhus Turns out that the Github username is already taken. I I was considering using hatchhq or something like that instead. Any suggestions?

**Comment by skovhus** [comment]
- hatch-sh
- hatch-community 😇
- hatchers
