### ISSUE TITLE
Woff2 mime-type support

### ISSUE THREAD

**Issue by Ragnar-H** [hatch-sh/hatch#50]
# Context
I was trying 🐣 out on a pet project which has [Font Awesome](http://fontawesome.io/) as a dependency.
[MimeTypes](https://docs.python.org/3/library/mimetypes.html) doesn't like `woff2` however, resulting in the following error
```
➜  flash-cards-react git:(master) ✗ hatch website deploy
Hatching...
Unknown content-type for ./dist/node_modules/font-awesome/fonts/fontawesome-webfont.woff2
```

# Fix
Add the mime-type in the same manner as for `.map` [here](https://github.com/hatch-sh/hatch/blob/master/hatch/services/website.py#L50)

```
def _upload_artifacts(self, bucket):
        mimetypes.add_type('application/json', '.map')
        mimetypes.add_type('application/woff2', '.woff2')
```

# Thoughts
I suppose this issue is more about if Hatch _should_ support use cases like this, and where to draw the line.

If so, I'll be happy to submit a PR with the 1 line of code 💪

**Comment by mads-hartmann** [comment]
@Ragnar-H Thanks a lot for giving it a go. Adding support for `.woff2` sounds like a good idea, please go ahead and submit a PR :)
